#ifndef PROJECT_BASE_FUNCTION_SOLUTION_DEFINE_H
#define PROJECT_BASE_FUNCTION_SOLUTION_DEFINE_H
#include <ProjectBase/cross_platform/util_method.hpp>
#include <ProjectBase/cross_platform/symbol.hpp>
#if defined(PROJECT_BASE_FUNCTION_SOLUTION)
#define PROJECT_BASE_FUNCTION_SOLUTION_SYMBOL SYMBOL_EXPORT
#else
#define PROJECT_BASE_FUNCTION_SOLUTION_SYMBOL SYMBOL_IMPORT
#endif // !1PROJECT_BASE_MULTI_LANGUAGE

#pragma message(MACRO_TO_STRING(PROJECT_BASE_FUNCTION_SOLUTION_SYMBOL))

#else
#endif // !1PROJET_BASE_MULTI_LANGUAGE_DEFINE_H


